### ISSUE TITLE
Sometimes messages seem to be duplicated in the console log

### ISSUE THREAD

**Issue by niklasfrykholm** [jims/atom-stingray#19]
![image](https://cloud.githubusercontent.com/assets/3582381/11865561/15f10414-a4a5-11e5-9f08-0ebad7dc6b51.png)

I'm guessing it is creating multiple web socket connections somehow.

**Comment by jims** [comment]
This is fixed in `a8ba51158a89f6a8c8beb5931061f7ef6f43f5df`
