### ISSUE TITLE
New Log Console tab is not created after selecting Run Project

### ISSUE THREAD

**Issue by matgis** [jims/atom-stingray#45]
Tested in a newly created Stingray project using the `basic_project` template. Choosing _Run Project_ from the menu initiates a compile and the game starts just fine, but I do not see a new tab appearing in the Log Console panel for the game output.

**Comment by niklasfrykholm** [comment]
Was this from `develop` -- the port range changes weren't merged.

**Comment by matgis** [comment]
That may very well be it. Has the changes been merged into `develop` now?

**Comment by niklasfrykholm** [comment]
Yes.

**Comment by matgis** [comment]
Works in `develop` now.
