### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by dashne** [jims/atom-stingray#52]
please, can you provide a step by step installation of this package,because I installed it by git and nothing happened,I just copied it manually to packages directory it gave to me rx error?!!!

**Comment by jims** [comment]
You'll be able to install it as any other package in the atom packages settings page once we publish the new version. We still have some issues to fix before we can do that though. If you want to use it in the mean time you can install it manually by runnig the following commands from the cloned repo path:

``` bash
$ apm install
$ apm link
```

**Comment by blitzvb** [comment]
that would be great. keep us updated.

**Comment by dashne** [comment]
its not working, giving rx error

**Comment by jims** [comment]
Make sure you remove the folder you copied into `~/.atom/packages` and run apm link after that.
